[project]
name = "chift-ai-toolkit"
version = "0.1.0"
description = "Chift OpenAPI AI Client"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "loguru>=0.7.3",
    "mcp>=1.4.1",
    "openai-agents>=0.0.6",
    "pydantic-ai>=0.0.43",
]
